### PR TITLE
fix conflict with dependency

### PR DESCRIPTION
**Pull request by Snoop05**
This overrides **${provides}** for _caja-gksu_ and below packages.

### CODE REVIEW

**Comment by nicman23** [comment]
the provides array is automatically populated from pkgname.

also again mate-meta is a horrid pkgbuild for the aur and should be dropped if and when this makes it into community

**Comment by nicman23** [comment]
I changed the caja-extensions PKGBUILD. Care to try it?

**Comment by danilobellini** [comment]
It's populated, but `caja-extensions-common-1.15-gtk3` is still missing that it provides / conflicts with the `caja-extensions-common` and `caja-extensions-common-gtk3`, as having the v1.12 installed avoids its installation without asking to replace: it conflicts after the package is built, as they have the same files.

**Comment by danilobellini** [comment]
I was thinking on make a PR to this but... it should be simpler, and I'll post here as I can't open a new issue: add a `-e 's/mate-meta-[^ ]*//'` to the sed command that creates the mate-meta `depends` list, or something alike. As of today, it depends on itself, rendering it unusable (`pacaur` complains that it has a cyclic dependency).

**Comment by nicman23** [comment]
huh pacaur did not complain for me / did not notice ... fixing it now :)

**Comment by nicman23** [comment]
fixed by removing element from array (on call)

**Comment by nicman23** [comment]
> having the v1.12 installed avoids its installation without asking to replace: it conflicts after the package is built, as they have the same files.

have you tested the PKGBUILD with the empty provides?

EDIT: I enabled the issues tab

**Comment by Snoop05** [comment]
not yet, will try tommorow

**Comment by nicman23** [comment]
You can now update from community to this with no issue.

**Pull request closed without merging**
