### PR TITLE
Fixed few make dependencies

### PR DESCRIPTION
**Pull request by Snoop05**
It wasn't possible to build every package in it's own clean build chroot, fixed now and tested.
('intltool' and 'gtk-doc')

### CODE REVIEW

**Comment by nicman23** [comment]
ok thanks uploading to the aur now.

**Comment by nicman23** [comment]
and done 👍

**Comment by Snoop05** [comment]
And i noticed few more bugs: 
1: **mate-meta** has no dependencies in PKGBUILD
2**: caja-gksu**, **caja-image-converter**, **caja-open-terminal**, **caja-sendto** and **caja-share** provides **caja-extensions** and **caja-extensions-gtk3** in .PKGINFO when built which makes them conflict with their dependency **caja-extensions-common**

I'll try to fix it in my forked repository and eventually pull request if it build alright.

**Comment by nicman23** [comment]
1. the mate-meta is for the aur and is generated in fast.sh
2. i will look into this when i have time

thanks

**Pull request merged**
